create table public.customer__details (
  id uuid not null default gen_random_uuid (),
  cognome text null,
  nome text null,
  cod_fis character varying null,
  ref_cognome text null,
  ref_nome text null,
  cl_celnum character varying null,
  cl_fixnum character varying null,
  email character varying null,
  pec character varying null,
  id_type uuid null,
  id_number character varying null,
  id_doc text null,
  doc_issuedate bigint null,
  doc_expdate bigint null,
  tit_birthplace text null,
  tit_birth_date text null,
  tit_gender character varying null,
  cust_address_1 text null,
  cust_address_2 text null,
  cust_zip bigint null,
  cust_town text null,
  cust_pr character varying null,
  virtual_bill text null,
  prev_virtual_bill text null,
  gdpr text null,
  status uuid null,
  constraint contact__details_pkey primary key (id),
  constraint customer__details_status_fkey foreign KEY (status) references customer__status (id) on update CASCADE on delete CASCADE,
  constraint customer__details_id_type_fkey foreign KEY (id_type) references id_document__types (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;